export const coffees = [
  {
    id: '001',
    type: ['tradicional'],
    title: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '002',
    type: ['tradicional'],
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '003',
    type: ['tradicional'],
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '004',
    type: ['tradicional', 'gelado'],
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '005',
    type: ['tradicional', 'com leite'],
    title: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '006',
    type: ['tradicional', 'com leite'],
    title: 'Latte',
    description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '007',
    type: ['tradicional', 'com leite'],
    title: 'Capuccino',
    description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '008',
    type: ['tradicional', 'com leite'],
    title: 'Macchiato',
    description: 'Café expresso misturado com um pouco de leite quente e espuma',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '009',
    type: ['tradicional', 'com leite'],
    title: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '010',
    type: ['especial', 'com leite'],
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '011',
    type: ['especial', 'alcoólico', 'gelado'],
    title: 'Cubano',
    description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '012',
    type: ['especial'],
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '013',
    type: ['especial'],
    title: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 990,
    amount: 10,
    available: true,
  },
  {
    id: '014',
    type: ['especial', 'alcoólico'],
    title: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 990,
    amount: 10,
    available: true,
  },
];
